### ISSUE TITLE
minsdkversion error

### ISSUE THREAD

**Issue by aardpro** [liuxiaoy/cordova-plugin-webview-crosswalk#4]
hi!
After I add this plugin and run cordova build --release,it always show errors:

D:\cordova\EPC\platforms\android\app\src\main\AndroidManifest.xml:13:5-74 Error:
        uses-sdk:minSdkVersion 16 cannot be smaller than version 19 declared in library [:CordovaLib] D:\cordova\EPC\platforms\android\CordovaLib\build\intermediates\manifests\full\release\AndroidManifest.xml as the library might be using APIs not available in 16
        Suggestion: use a compatible library with a minSdk of at most 16,
                or increase this project's minSdk version to at least 19,
                or use tools:overrideLibrary="org.apache.cordova" to force usage (may lead to runtime failures)

How to do?

**Comment by liuxiaoy** [comment]
这个插件在plugin.xml中默认定义了
```
<preference name="android-minSdkVersion" value="16" />
```
解决方案：在你的项目config.xml中加入
```
<preference name="android-minSdkVersion" value="19" />
```
